FROM caddy:2-builder AS builder

ENV GOPROXY=https://goproxy.cn,direct

RUN xcaddy build \
    --with github.com/caddy-dns/tencentcloud

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
